packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  quickjs-wasi: ^2.2.0
  '@types/async-retry': ^1.4.5
  '@types/debug': ^4.1.7
  '@types/node': ^22.13.0
  '@types/ws': ^8.5.4
  async-listen: ^3.0.0
  async-retry: ^1.3.3
  debug: ^4.3.4
  socksv5: 'github:TooTallNate/socksv5#d937368b28e929396166d77a06d387a4a902bd51'
  typescript: ^5.1.6
  ws: ^8.13.0
